name: wissance-zerial
version: '1.0'
grade: stable
summary: Utility for interaction with multiple RS232 (COM) devices
description: |
  Fast and convenient utility to communicate with any RS232 device, useful especially for hardware developers.

base: core22

architectures:
  - build-on: [amd64]
    build-for: [amd64]

confinement: strict

parts:
  wissance-zerial:
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    source: ./app/Wissance.Zerial
    build-packages:
      - dotnet-sdk-8.0
    stage-packages:
      - libfontconfig
      - libicu70
      - libx11-6
      - libstdc++5
      - libice6
      - libsm6
    override-build: |
      dotnet build -c Release
      dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true -o $SNAPCRAFT_PART_INSTALL ./Wissance.Zerial.Desktop/Wissance.Zerial.Desktop.csproj
      chmod 0755 $SNAPCRAFT_PART_INSTALL

apps:
  wissance-zerial:
    plugs:
      - desktop
      - desktop-legacy
    command: ./Wissance.Zerial.Desktop --snap
