name: wissance-zerial
version: '1.2.1'
grade: stable
summary: Utility for interaction with multiple RS232 (COM) devices
description: |
  Fast and convenient utility to communicate with any RS232 device, useful especially for hardware developers.

base: core22

architectures:
  - build-on: [amd64]
    build-for: [amd64]

confinement: strict

parts:
  wissance-assets:
    plugin: dump
    source: ./app/Wissance.Zerial/Wissance.Zerial.Desktop/Assets
    organize:
      '*': 'Assets/'
  wissance-zerial:
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    source: ./app/Wissance.Zerial
    build-packages:
      - dotnet-sdk-8.0
    stage-packages:
      - libgl1-mesa-glx
      - libgl1-mesa-dri
      - libfontconfig
      - libicu70
      - libx11-6
      - libstdc++6
      - libice6
      - libsm6
    override-build: |
      dotnet build -c Release
      dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true -o $SNAPCRAFT_PART_INSTALL ./Wissance.Zerial.Desktop/Wissance.Zerial.Desktop.csproj
      chmod 0755 $SNAPCRAFT_PART_INSTALL
  wrapper-script:
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      cat << 'EOF' > $CRAFT_PART_INSTALL/bin/desktop-wrapper
      #!/bin/sh
      exec "$SNAP/Wissance.Zerial.Desktop" --environment=snap "$@"
      EOF
      chmod +x $CRAFT_PART_INSTALL/bin/desktop-wrapper

apps:
  wissance-zerial:
    extensions: [ gnome ]
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
      - gsettings
      - opengl
      - wissance-zerial-serial-port
    command: snap/command-chain/desktop-launch bin/desktop-wrapper
    environment:
      LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri:${LD_LIBRARY_PATH}
plugs:
   wissance-zerial-serial-port:
      interface: serial-port
